FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nginx
ARG PORTA_ARG
EXPOSE ${PORTA_ARG}
CMD ["nginx", "-g", "daemon off;"]

# docker build -t server-1 --build-arg PORTA_ARG=7000 . --no-cache
# docker run -d --name server-com-arg -p 7000:80 server-1
