import "bootstrap/dist/css/bootstrap.min.css";

import type { Metadata } from "next";
import { Navbar } from "./components/Navbar/Navbar";
import BootstrapClient from "./components/Clients/BootstrapClient";
import { ReactQueryClientProvider } from "./components/Clients/ReactQueryClient";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata: Metadata = {
  title: "WA Loja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <Navbar />
          {children}
          <BootstrapClient />
          <ReactQueryDevtools initialIsOpen={false} />
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
